[tool.mypy]
ignore_missing_imports = true
mypy_path = ["ansible_collections/platform42/neo4j/plugins"]
strict = true

[tool.pylint.DESIGN]
max-locals = 25
max-line-length = 120
max-returns = 10
max-args = 8
max-positional-arguments = 8

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116"   # missing-function-docstring
]