[tool.mypy]
ignore_missing_imports = true
mypy_path = ["ansible_collections/platform42/neo4j/plugins"]
strict = true

[tool.pylint.DESIGN]
max-locals = 25
max-line-length = 120
max-returns = 10
max-positional-arguments = 6