[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
namespace_packages = true
explicit_package_bases = true
packages = [
    "ansible_collections.platform42.neo4j"
]

# Ignore Ansible-provided module_utils (global)
[[tool.mypy.overrides]]
module = "ansible.*"
ignore_missing_imports = true

# Fully check your collectionâ€™s local module_utils and modules
[[tool.mypy.overrides]]
module = "ansible_collections.platform42.neo4j.*"
ignore_missing_imports = false

[tool.pylint.FORMAT]
max-line-length = 140

[tool.pylint.DESIGN]
max-locals = 25
max-line-length = 120
max-returns = 10
max-args = 10
max-positional-arguments = 10

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116"   # missing-function-docstring
]